

runtime: php72
instance_class: F1
automatic_scaling:
  max_idle_instances: 1  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms


handlers:


- url: /public/(.*)
  static_files: public/\1
  upload: public/(.*)

- url: /
  script: auto

- url: /(.+)
  script: auto